"""Comparison content. Competitor facts are kept to widely documented, durable traits;
pricing is described qualitatively and readers are told to verify current rates."""

APP = {
    "name": "Nanolaunch",
    "window": "Stays listed; ranks on Today / Week / Month boards",
    "free": "Yes, launching is free",
    "paid": "None. No paid placements",
    "best": "Indie makers and small teams who want feedback and steady discovery",
    "reach": "New, growing community (smaller than the big incumbents)",
    "feedback": "Upvotes, Idea and Product ratings, comments",
    "ai": "Yes, AI launch-copy assistant from your URL",
    "ease": "Fast: paste a URL, review the AI draft, publish",
}

ORIGINAL = {
    "slug": "microlaunch",
    "name": "Microlaunch",
    "url": "https://microlaunch.net/",
    "blurb": "The closest comparison: both are launch platforms with leaderboards for indie products.",
    "window": "Monthly leaderboard with weekly view; launches stay listed",
    "free": "Yes, free launches",
    "paid": "Premium / Pro launches, sponsorships and paid deal listings",
    "best": "Makers who also want deals, hackathons and sponsor exposure",
    "reach": "Established indie audience with deals and community sections",
    "feedback": "Ratings for idea and product, roasts, comments",
    "ai": "No built-in AI launch-copy tool that we know of",
    "ease": "Straightforward, with more sections to navigate",
    "pros": ["Established community and a broad feature set (deals, hackathons, stories)",
             "Month and week leaderboards with Business / Consumer filters",
             "Paid options exist for makers who want extra visibility"],
    "cons": ["Many sections and paid upsells can feel busy for a first launch",
             "Premium placements mean organic listings compete with sponsored ones"],
    "verdict": "Microlaunch has the bigger community today and extras like deals and hackathons. Nanolaunch is the simpler, fully free alternative with an AI assistant that drafts your launch copy. If you want one clean place to launch and get feedback with no paid tiers, try Nanolaunch; if deals and sponsorship exposure matter, Microlaunch is the better fit.",
}

COMPETITORS = [
    {"slug": "product-hunt", "name": "Product Hunt", "url": "https://www.producthunt.com/",
     "blurb": "The biggest launch audience, but a single 24-hour sprint. See when a calmer board wins.",
     "window": "Daily (roughly 24-hour ranking cycle)", "free": "Yes, free to launch",
     "paid": "Optional promotion and ads; check their current pricing",
     "best": "Products that can mobilize a big audience on one day",
     "reach": "Very large, mainstream tech audience", "feedback": "Upvotes and comments",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Simple to submit, high pressure on launch day",
     "pros": ["Unmatched reach and brand recognition", "Strong press and investor visibility", "Free to launch"],
     "cons": ["One-day window rewards pre-built audiences", "Crowded: new products can vanish quickly"],
     "verdict": "If you can rally a large audience for one day, Product Hunt's reach is hard to beat. If you are a solo maker without a following, Nanolaunch's persistent weekly and monthly boards give a launch more time to be found. Many makers use both."},
    {"slug": "uneed", "name": "Uneed", "url": "https://www.uneed.best/",
     "blurb": "A daily board with a launch queue. Compare queues, boards and cost.",
     "window": "Daily board, listings persist", "free": "Yes, via a free queue",
     "paid": "Paid option to skip the queue; check current rates",
     "best": "Indie makers wanting a calmer daily board",
     "reach": "Moderate indie audience", "feedback": "Upvotes and comments",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Easy submission; free tier means waiting in a queue",
     "pros": ["Calmer than Product Hunt", "Listings persist after launch day", "Paid fast-track available"],
     "cons": ["Free launches may wait in a queue", "Smaller audience than the incumbents"],
     "verdict": "Uneed is a solid, low-noise board. Nanolaunch has no queue or paid skip-the-line tier, and drafts your launch copy with AI, which makes it quicker to go live. Uneed may have a larger audience for some niches, so check both."},
    {"slug": "peerlist-launchpad", "name": "Peerlist Launchpad", "url": "https://peerlist.io/launchpad",
     "blurb": "A weekly launch cycle tied to maker profiles. See which suits your product.",
     "window": "Weekly cycle", "free": "Yes, free to launch",
     "paid": "Peerlist has paid professional features; check current pricing",
     "best": "Makers whose personal profile and credibility matter",
     "reach": "Professional builder network", "feedback": "Upvotes, comments, profile follows",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Easy if you already have a Peerlist profile",
     "pros": ["Launches link to a professional maker profile", "Weekly cycle is less frantic than daily", "Good for networking"],
     "cons": ["Value depends on building a Peerlist profile", "Weekly cycles mean fewer chances to reappear"],
     "verdict": "Peerlist suits makers who want launches tied to a professional profile. Nanolaunch is lighter: no profile build-out, rolling Today/Week/Month boards, and AI-drafted copy. Pick Peerlist for networking, Nanolaunch for speed."},
    {"slug": "fazier", "name": "Fazier", "url": "https://fazier.com/",
     "blurb": "A daily leaderboard known for backlinks. Compare discovery, SEO value and cost.",
     "window": "Daily leaderboard", "free": "Yes, free launches",
     "paid": "Optional paid promotion; check current pricing",
     "best": "Makers who want a backlink and daily exposure",
     "reach": "Moderate, less crowded than Product Hunt", "feedback": "Upvotes and comments",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Simple submission",
     "pros": ["Less crowded than the biggest boards", "Guides describe do-follow backlinks as an SEO benefit", "Daily exposure"],
     "cons": ["Smaller audience", "Daily ranking still favors launches with an upvote push"],
     "verdict": "Fazier is a reasonable daily board and often cited for backlinks. Nanolaunch adds Idea/Product ratings, longer-lived weekly and monthly boards and an AI copy assistant. Submitting to both costs little."},
    {"slug": "devhunt", "name": "DevHunt", "url": "https://devhunt.org/",
     "blurb": "A weekly board with GitHub verification for developer tools.",
     "window": "Weekly board", "free": "Yes, free to launch",
     "paid": "Optional paid promotion; check current pricing",
     "best": "Developer tools and open source projects",
     "reach": "Developer-focused audience", "feedback": "Upvotes and comments from developers",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Easy; GitHub sign-in",
     "pros": ["Developer-focused audience", "GitHub verification builds trust", "Great for open source"],
     "cons": ["Narrow focus: not ideal for consumer or non-technical products"],
     "verdict": "For a developer tool, DevHunt's audience is hard to replace. For anything broader, Nanolaunch covers dev tools, AI, productivity and consumer products on one board with AI-assisted listings."},
    {"slug": "betalist", "name": "BetaList", "url": "https://betalist.com/",
     "blurb": "A pre-launch directory for waitlists and beta signups. Different job, so compare.",
     "window": "Curated queue, then listing", "free": "Free submission with a review queue",
     "paid": "Paid option to be featured sooner; check current pricing",
     "best": "Pre-launch startups collecting waitlist signups",
     "reach": "Early adopters who like trying betas", "feedback": "Signups and a curated audience",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Simple, but curated, so expect a wait",
     "pros": ["Built for early adopters and beta testers", "Curation signals quality", "Strong for waitlists"],
     "cons": ["Focused on pre-launch rather than ongoing leaderboards", "Review queue can be slow"],
     "verdict": "BetaList is for collecting early signups before launch. Nanolaunch is for the launch itself and ongoing ranking. They complement each other, and many makers list on both."},
    {"slug": "tinylaunch", "name": "TinyLaunch", "url": "https://www.tinylaun.ch/",
     "blurb": "A lightweight launch site for indie side projects. Compare features and feedback.",
     "window": "Daily / lightweight listing", "free": "Yes, free to launch",
     "paid": "Optional paid placement; check current pricing",
     "best": "Side projects and small indie products",
     "reach": "Small indie audience", "feedback": "Upvotes",
     "ai": "No dedicated AI launch-copy tool that we know of", "ease": "Very simple",
     "pros": ["Lightweight and easy to use", "Friendly to tiny side projects"],
     "cons": ["Small audience", "Fewer feedback tools"],
     "verdict": "TinyLaunch keeps things very light. Nanolaunch is similarly easy but adds ratings, comments and an AI launch assistant. If you want richer feedback from the same effort, choose Nanolaunch."},
]

ROWS = [("Launch window", "window"), ("Free to launch", "free"), ("Paid options", "paid"),
        ("Best for", "best"), ("Audience reach", "reach"), ("Feedback", "feedback"),
        ("AI launch-copy assistant", "ai"), ("Ease of use", "ease")]

APP_PROS = ["Completely free: no paid tiers or sponsored placements",
            "AI drafts your tagline, description, features and first comment from a URL",
            "Today / Week / Month leaderboards so a launch is not a one-day sprint",
            "Idea and Product ratings give structured feedback, not just upvotes"]
APP_CONS = ["Newer, so the audience is smaller than established platforms",
            "No deals marketplace or hackathons (yet)"]


def all_entries():
    return COMPETITORS + [ORIGINAL]


def faqs(c):
    n = c["name"]
    return [
        (f"Is Nanolaunch a good {n} alternative?",
         f"Yes, if you want a free launch board with persistent rankings and an AI assistant. {c['verdict']}"),
        (f"{n} vs Nanolaunch: which is better?",
         f"It depends on your goal. {n} is best for: {c['best'].lower()}. Nanolaunch is best for: {APP['best'].lower()}."),
        (f"Is Nanolaunch free compared to {n}?",
         f"Launching on Nanolaunch is free with no paid placements. {n}: {c['free'].lower()}; paid options: {c['paid'].lower()}."),
        (f"Can I launch on both {n} and Nanolaunch?",
         "Yes. Most makers list on several platforms. Nothing stops you from launching on both, and each can bring different visitors."),
        (f"What are the best {n} alternatives?",
         "Popular options include " + ", ".join(x["name"] for x in all_entries() if x["slug"] != c["slug"]) + " and Nanolaunch. Browse them all in our comparison hub."),
    ]
